# Generated by Django 4.2.1 on 2023-06-11 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemBookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bookitem')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orderitem')),
            ],
            options={
                'verbose_name': 'Order Item Book Item',
                'verbose_name_plural': 'Order Item Book Items',
            },
        ),
    ]
