# Generated by Django 4.2.1 on 2023-06-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_orderitembookitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemBookItem',
        ),
    ]
