# Generated by Django 4.2.1 on 2023-06-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_orderitembookitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitembookitem',
            name='book_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.bookitem'),
        ),
    ]
